-- ============================================
-- MIGRAÇÃO: Garantir TODAS as colunas da tabela clientes
-- Idempotente (ADD COLUMN IF NOT EXISTS) — adiciona apenas o que faltar.
-- Corrige erro de importação "Could not find the 'website' column ... in the schema cache"
-- causado por banco ao vivo fora de sincronia com as migrations.
-- ============================================

ALTER TABLE clientes ADD COLUMN IF NOT EXISTS razao_social            TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS nome_fantasia           TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cnpj                    TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_nome            TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_telefone        TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_celular         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_telefone_fixo   TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_email           TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco                TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_rua            TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_numero         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_complemento    TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_bairro         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_cidade         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_estado         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_cep            TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cnpj2                   TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_rua2           TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_numero2        TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_complemento2   TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_bairro2        TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_cidade2        TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_estado2        TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS endereco_cep2           TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cnae_primario           TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS cnae_secundario         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS redes_sociais           TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS whatsapp                TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS omie_codigo             TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS etapa                   TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS etapa_anterior          TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_entrada_etapa      DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS vendedor_id             INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS score                   INTEGER DEFAULT 0;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS valor_estimado          NUMERIC(12, 2);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS produtos_interesse      JSONB;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS ultima_interacao        DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS dias_inativo            INTEGER DEFAULT 0;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_envio_amostra      DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS status_amostra          TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_homologacao        DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS proximo_pedido_previsto DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS valor_proposta          NUMERIC(12, 2);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_proposta           DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS status_entrega          TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_entrega_prevista   DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_entrega_realizada  DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS status_faturamento      TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_ultimo_pedido      DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS motivo_perda            TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS categoria_perda         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_perda              DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS resultado_amostra       TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_resultado_amostra  DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS motivo_reprovacao       TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS status_follow_up        TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS status_satisfacao       TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS nota_satisfacao         INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS feedback_satisfacao     TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS ciclo_recompra          INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_proxima_recompra   DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS total_compras           INTEGER DEFAULT 0;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS omie_status_logistico   TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS omie_codigo_rastreio    TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS omie_nota_fiscal        TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS omie_data_faturamento   DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS origem_lead             TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS notas                   TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS segmento                TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS localizacao             TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS tentativa_amostra       INTEGER DEFAULT 0;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS whatsapp_valido         BOOLEAN;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS whatsapp_jid            TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS whatsapp_validado_em    TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS novo_ciclo              BOOLEAN;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS ciclo_numero            INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS google_place_id         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS google_rating           NUMERIC(3, 1);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS google_reviews          INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS website                 TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS latitude                NUMERIC(10, 6);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS longitude               NUMERIC(10, 6);
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS status_cliente          TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_ultima_amostra     DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_ultima_venda       DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS grupo_economico_id      INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS instagram               TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS facebook                TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS linkedin                TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_financeiro_nome TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_financeiro_telefone TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_compras_nome    TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS contato_compras_telefone TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS produtos_quantidades_mensais JSONB;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS motivo_inativacao       TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS data_inativacao         DATE;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS inativado_por           INTEGER;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS inativado_por_abandono  BOOLEAN;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS descricao               TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS criado_em               TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS criado_por_nome         TEXT;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS atualizado_em           TIMESTAMPTZ DEFAULT NOW();

-- Recarregar o cache de schema do PostgREST para reconhecer as novas colunas imediatamente
NOTIFY pgrst, 'reload schema';
