-- ============================================
-- MIGRAÇÃO: Schema base da tabela clientes
-- (caso a tabela ainda não exista no projeto)
-- ============================================
CREATE TABLE IF NOT EXISTS clientes (
  id                      SERIAL PRIMARY KEY,
  razao_social            TEXT NOT NULL,
  nome_fantasia           TEXT,
  cnpj                    TEXT,
  contato_nome            TEXT,
  contato_telefone        TEXT,
  contato_celular         TEXT,
  contato_telefone_fixo   TEXT,
  contato_email           TEXT,
  endereco                TEXT,
  endereco_rua            TEXT,
  endereco_numero         TEXT,
  endereco_complemento    TEXT,
  endereco_bairro         TEXT,
  endereco_cidade         TEXT,
  endereco_estado         TEXT,
  endereco_cep            TEXT,
  cnpj2                   TEXT,
  endereco_rua2           TEXT,
  endereco_numero2        TEXT,
  endereco_complemento2   TEXT,
  endereco_bairro2        TEXT,
  endereco_cidade2        TEXT,
  endereco_estado2        TEXT,
  endereco_cep2           TEXT,
  cnae_primario           TEXT,
  cnae_secundario         TEXT,
  redes_sociais           JSONB,
  whatsapp                TEXT,
  omie_codigo             TEXT,
  etapa                   TEXT NOT NULL DEFAULT 'prospecto',
  etapa_anterior          TEXT,
  data_entrada_etapa      DATE,
  vendedor_id             INTEGER REFERENCES vendedores(id) ON DELETE SET NULL,
  score                   INTEGER DEFAULT 0,
  valor_estimado          NUMERIC(12, 2),
  produtos_interesse      JSONB,
  ultima_interacao        DATE,
  dias_inativo            INTEGER DEFAULT 0,
  data_envio_amostra      DATE,
  status_amostra          TEXT,
  data_homologacao        DATE,
  proximo_pedido_previsto DATE,
  valor_proposta          NUMERIC(12, 2),
  data_proposta           DATE,
  status_entrega          TEXT,
  data_entrega_prevista   DATE,
  data_entrega_realizada  DATE,
  status_faturamento      TEXT,
  data_ultimo_pedido      DATE,
  motivo_perda            TEXT,
  categoria_perda         TEXT,
  data_perda              DATE,
  resultado_amostra       TEXT,
  data_resultado_amostra  DATE,
  motivo_reprovacao       TEXT,
  status_follow_up        TEXT,
  status_satisfacao       TEXT,
  nota_satisfacao         INTEGER,
  feedback_satisfacao     TEXT,
  ciclo_recompra          INTEGER,
  data_proxima_recompra   DATE,
  total_compras           INTEGER DEFAULT 0,
  omie_status_logistico   TEXT,
  omie_codigo_rastreio    TEXT,
  omie_nota_fiscal        TEXT,
  omie_data_faturamento   DATE,
  origem_lead             TEXT,
  notas                   TEXT,
  segmento                TEXT,
  localizacao             TEXT,
  tentativa_amostra       INTEGER DEFAULT 0,
  whatsapp_valido         BOOLEAN,
  whatsapp_jid            TEXT,
  whatsapp_validado_em    TEXT,
  novo_ciclo              BOOLEAN,
  ciclo_numero            INTEGER,
  google_place_id         TEXT,
  google_rating           NUMERIC(3, 1),
  google_reviews          INTEGER,
  website                 TEXT,
  latitude                NUMERIC(10, 6),
  longitude               NUMERIC(10, 6),
  status_cliente          TEXT,
  data_ultima_amostra     DATE,
  data_ultima_venda       DATE,
  grupo_economico_id      INTEGER,
  instagram               TEXT,
  facebook                TEXT,
  linkedin                TEXT,
  contato_financeiro_nome TEXT,
  contato_financeiro_telefone TEXT,
  contato_compras_nome    TEXT,
  contato_compras_telefone TEXT,
  produtos_quantidades_mensais JSONB,
  motivo_inativacao       TEXT,
  data_inativacao         DATE,
  inativado_por           INTEGER,
  inativado_por_abandono  BOOLEAN,
  descricao               TEXT,
  criado_em               TIMESTAMPTZ DEFAULT NOW(),
  criado_por_nome         TEXT,
  atualizado_em           TIMESTAMPTZ DEFAULT NOW(),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clientes_vendedor_id ON clientes(vendedor_id);
CREATE INDEX IF NOT EXISTS idx_clientes_etapa ON clientes(etapa);
CREATE INDEX IF NOT EXISTS idx_clientes_cnpj ON clientes(cnpj);
CREATE INDEX IF NOT EXISTS idx_clientes_status_cliente ON clientes(status_cliente);
CREATE INDEX IF NOT EXISTS idx_clientes_grupo_economico_id ON clientes(grupo_economico_id);
